#pragma once

#define UNDEFINED -1
#define SUCCESS 0
#define INVALID_PATH 1
#define INVALID_CONFIG 2
#define ELEMENT_NOT_FOUND 3
#define INVALID_INDEX 4
#define DUPLICATE_ELEMENT 5
#define INVALID_VALUE 6